using System.Collections.Generic;
using RimWorld;
using Verse;

namespace JustStart
{
    /// <summary>
    /// Holds non-colonist starting pawns (hostile guards, prisoners) generated by JustStartFlow
    /// until the starting map actually exists, then spawns/places them. Cleared after use.
    /// </summary>
    public static class JustStartMapSpawnQueue
    {
        private static List<(Pawn pawn, PawnRole role)> pending = new List<(Pawn, PawnRole)>();

        public static void Enqueue(List<(Pawn pawn, PawnRole role)> pawns) => pending.AddRange(pawns);

        public static void SpawnAllOn(Map map)
        {
            foreach (var (pawn, role) in pending)
            {
                IntVec3 cell = role.faction == PawnRoleFaction.HostileOnMap
                    ? CellFinder.RandomNotEdgeCell(10, map)
                    : map.Center;

                GenSpawn.Spawn(pawn, CellFinder.RandomClosewalkCellNear(cell, map, 10), map);

                if (role.faction == PawnRoleFaction.PlayerPrisoner)
                    pawn.guest?.SetGuestStatus(Faction.OfPlayer, GuestStatus.Prisoner);
            }

            pending.Clear();
        }
    }
}
